// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientMessage } from './ClientMessage';
import {
    ClientMessageFromJSON,
    ClientMessageFromJSONTyped,
    ClientMessageToJSON,
    ClientMessageToJSONTyped,
} from './ClientMessage';

/**
 * 
 * @export
 * @interface ChatRequest
 */
export interface ChatRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<ClientMessage>}
     * @memberof ChatRequest
     */
    messages?: Array<ClientMessage> | null;
    /**
     * 
     * @type {ClientMessage}
     * @memberof ChatRequest
     */
    message?: ClientMessage | null;
    /**
     * 
     * @type {string}
     * @memberof ChatRequest
     */
    id?: string | null;
}

/**
 * Check if a given object implements the ChatRequest interface.
 */
export function instanceOfChatRequest(value: object): value is ChatRequest {
    return true;
}

export function ChatRequestFromJSON(json: any): ChatRequest {
    return ChatRequestFromJSONTyped(json, false);
}

export function ChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(ClientMessageFromJSON)),
        'message': json['message'] == null ? undefined : ClientMessageFromJSON(json['message']),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ChatRequestToJSON(json: any): ChatRequest {
    return ChatRequestToJSONTyped(json, false);
}

export function ChatRequestToJSONTyped(value?: ChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(ClientMessageToJSON)),
        'message': ClientMessageToJSON(value['message']),
        'id': value['id'],
    };
}

