// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolInvocation } from './ToolInvocation';
import {
    ToolInvocationFromJSON,
    ToolInvocationFromJSONTyped,
    ToolInvocationToJSON,
    ToolInvocationToJSONTyped,
} from './ToolInvocation';
import type { ClientAttachment } from './ClientAttachment';
import {
    ClientAttachmentFromJSON,
    ClientAttachmentFromJSONTyped,
    ClientAttachmentToJSON,
    ClientAttachmentToJSONTyped,
} from './ClientAttachment';
import type { ClientMessagePart } from './ClientMessagePart';
import {
    ClientMessagePartFromJSON,
    ClientMessagePartFromJSONTyped,
    ClientMessagePartToJSON,
    ClientMessagePartToJSONTyped,
} from './ClientMessagePart';

/**
 * 
 * @export
 * @interface ClientMessage
 */
export interface ClientMessage {
    /**
     * 
     * @type {string}
     * @memberof ClientMessage
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof ClientMessage
     */
    content?: string | null;
    /**
     * 
     * @type {Array<ClientMessagePart>}
     * @memberof ClientMessage
     */
    parts?: Array<ClientMessagePart> | null;
    /**
     * 
     * @type {Array<ClientAttachment>}
     * @memberof ClientMessage
     */
    experimentalAttachments?: Array<ClientAttachment> | null;
    /**
     * 
     * @type {Array<ToolInvocation>}
     * @memberof ClientMessage
     */
    toolInvocations?: Array<ToolInvocation> | null;
}

/**
 * Check if a given object implements the ClientMessage interface.
 */
export function instanceOfClientMessage(value: object): value is ClientMessage {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ClientMessageFromJSON(json: any): ClientMessage {
    return ClientMessageFromJSONTyped(json, false);
}

export function ClientMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'parts': json['parts'] == null ? undefined : ((json['parts'] as Array<any>).map(ClientMessagePartFromJSON)),
        'experimentalAttachments': json['experimental_attachments'] == null ? undefined : ((json['experimental_attachments'] as Array<any>).map(ClientAttachmentFromJSON)),
        'toolInvocations': json['toolInvocations'] == null ? undefined : ((json['toolInvocations'] as Array<any>).map(ToolInvocationFromJSON)),
    };
}

export function ClientMessageToJSON(json: any): ClientMessage {
    return ClientMessageToJSONTyped(json, false);
}

export function ClientMessageToJSONTyped(value?: ClientMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
        'parts': value['parts'] == null ? undefined : ((value['parts'] as Array<any>).map(ClientMessagePartToJSON)),
        'experimental_attachments': value['experimentalAttachments'] == null ? undefined : ((value['experimentalAttachments'] as Array<any>).map(ClientAttachmentToJSON)),
        'toolInvocations': value['toolInvocations'] == null ? undefined : ((value['toolInvocations'] as Array<any>).map(ToolInvocationToJSON)),
    };
}

