// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientMessagePart
 */
export interface ClientMessagePart {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ClientMessagePart
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ClientMessagePart
     */
    text?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientMessagePart
     */
    contentType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientMessagePart
     */
    url?: string | null;
    /**
     * 
     * @type {}
     * @memberof ClientMessagePart
     */
    data?:  | null;
    /**
     * 
     * @type {string}
     * @memberof ClientMessagePart
     */
    toolCallId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientMessagePart
     */
    toolName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientMessagePart
     */
    state?: string | null;
    /**
     * 
     * @type {}
     * @memberof ClientMessagePart
     */
    input?:  | null;
    /**
     * 
     * @type {}
     * @memberof ClientMessagePart
     */
    output?:  | null;
    /**
     * 
     * @type {}
     * @memberof ClientMessagePart
     */
    args?:  | null;
}

/**
 * Check if a given object implements the ClientMessagePart interface.
 */
export function instanceOfClientMessagePart(value: object): value is ClientMessagePart {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ClientMessagePartFromJSON(json: any): ClientMessagePart {
    return ClientMessagePartFromJSONTyped(json, false);
}

export function ClientMessagePartFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientMessagePart {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'text': json['text'] == null ? undefined : json['text'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'url': json['url'] == null ? undefined : json['url'],
        'data': json['data'] == null ? undefined : FromJSON(json['data']),
        'toolCallId': json['toolCallId'] == null ? undefined : json['toolCallId'],
        'toolName': json['toolName'] == null ? undefined : json['toolName'],
        'state': json['state'] == null ? undefined : json['state'],
        'input': json['input'] == null ? undefined : FromJSON(json['input']),
        'output': json['output'] == null ? undefined : FromJSON(json['output']),
        'args': json['args'] == null ? undefined : FromJSON(json['args']),
    };
}

export function ClientMessagePartToJSON(json: any): ClientMessagePart {
    return ClientMessagePartToJSONTyped(json, false);
}

export function ClientMessagePartToJSONTyped(value?: ClientMessagePart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'text': value['text'],
        'contentType': value['contentType'],
        'url': value['url'],
        'data': ToJSON(value['data']),
        'toolCallId': value['toolCallId'],
        'toolName': value['toolName'],
        'state': value['state'],
        'input': ToJSON(value['input']),
        'output': ToJSON(value['output']),
        'args': ToJSON(value['args']),
    };
}

