// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientAttachment
 */
export interface ClientAttachment {
    /**
     * 
     * @type {string}
     * @memberof ClientAttachment
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAttachment
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAttachment
     */
    url: string;
}

/**
 * Check if a given object implements the ClientAttachment interface.
 */
export function instanceOfClientAttachment(value: object): value is ClientAttachment {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ClientAttachmentFromJSON(json: any): ClientAttachment {
    return ClientAttachmentFromJSONTyped(json, false);
}

export function ClientAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'contentType': json['contentType'],
        'url': json['url'],
    };
}

export function ClientAttachmentToJSON(json: any): ClientAttachment {
    return ClientAttachmentToJSONTyped(json, false);
}

export function ClientAttachmentToJSONTyped(value?: ClientAttachment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'contentType': value['contentType'],
        'url': value['url'],
    };
}

