// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNewChatResponse
 */
export interface CreateNewChatResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateNewChatResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CreateNewChatResponse interface.
 */
export function instanceOfCreateNewChatResponse(value: object): value is CreateNewChatResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreateNewChatResponseFromJSON(json: any): CreateNewChatResponse {
    return CreateNewChatResponseFromJSONTyped(json, false);
}

export function CreateNewChatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNewChatResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
    };
}

export function CreateNewChatResponseToJSON(json: any): CreateNewChatResponse {
    return CreateNewChatResponseToJSONTyped(json, false);
}

export function CreateNewChatResponseToJSONTyped(value?: CreateNewChatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
    };
}

