// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChatMessagesResponse
 */
export interface GetChatMessagesResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof GetChatMessagesResponse
     */
    id: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof GetChatMessagesResponse
     */
    messages: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the GetChatMessagesResponse interface.
 */
export function instanceOfGetChatMessagesResponse(value: object): value is GetChatMessagesResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function GetChatMessagesResponseFromJSON(json: any): GetChatMessagesResponse {
    return GetChatMessagesResponseFromJSONTyped(json, false);
}

export function GetChatMessagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChatMessagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'messages': json['messages'],
    };
}

export function GetChatMessagesResponseToJSON(json: any): GetChatMessagesResponse {
    return GetChatMessagesResponseToJSONTyped(json, false);
}

export function GetChatMessagesResponseToJSONTyped(value?: GetChatMessagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'messages': value['messages'],
    };
}

