// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolInvocationState } from './ToolInvocationState';
import {
    ToolInvocationStateFromJSON,
    ToolInvocationStateFromJSONTyped,
    ToolInvocationStateToJSON,
    ToolInvocationStateToJSONTyped,
} from './ToolInvocationState';

/**
 * 
 * @export
 * @interface ToolInvocation
 */
export interface ToolInvocation {
    /**
     * 
     * @type {ToolInvocationState}
     * @memberof ToolInvocation
     */
    state: ToolInvocationState;
    /**
     * 
     * @type {string}
     * @memberof ToolInvocation
     */
    toolCallId: string;
    /**
     * 
     * @type {string}
     * @memberof ToolInvocation
     */
    toolName: string;
    /**
     * 
     * @type {any}
     * @memberof ToolInvocation
     */
    args: any | null;
    /**
     * 
     * @type {any}
     * @memberof ToolInvocation
     */
    result: any | null;
}



/**
 * Check if a given object implements the ToolInvocation interface.
 */
export function instanceOfToolInvocation(value: object): value is ToolInvocation {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('toolCallId' in value) || value['toolCallId'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('args' in value) || value['args'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ToolInvocationFromJSON(json: any): ToolInvocation {
    return ToolInvocationFromJSONTyped(json, false);
}

export function ToolInvocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolInvocation {
    if (json == null) {
        return json;
    }
    return {
        
        'state': ToolInvocationStateFromJSON(json['state']),
        'toolCallId': json['toolCallId'],
        'toolName': json['toolName'],
        'args': json['args'],
        'result': json['result'],
    };
}

export function ToolInvocationToJSON(json: any): ToolInvocation {
    return ToolInvocationToJSONTyped(json, false);
}

export function ToolInvocationToJSONTyped(value?: ToolInvocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': ToolInvocationStateToJSON(value['state']),
        'toolCallId': value['toolCallId'],
        'toolName': value['toolName'],
        'args': value['args'],
        'result': value['result'],
    };
}

