// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ToolInvocationState = {
    Call: 'call',
    PartialCall: 'partial-call',
    Result: 'result'
} as const;
export type ToolInvocationState = typeof ToolInvocationState[keyof typeof ToolInvocationState];


export function instanceOfToolInvocationState(value: any): boolean {
    for (const key in ToolInvocationState) {
        if (Object.prototype.hasOwnProperty.call(ToolInvocationState, key)) {
            if (ToolInvocationState[key as keyof typeof ToolInvocationState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ToolInvocationStateFromJSON(json: any): ToolInvocationState {
    return ToolInvocationStateFromJSONTyped(json, false);
}

export function ToolInvocationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolInvocationState {
    return json as ToolInvocationState;
}

export function ToolInvocationStateToJSON(value?: ToolInvocationState | null): any {
    return value as any;
}

export function ToolInvocationStateToJSONTyped(value: any, ignoreDiscriminator: boolean): ToolInvocationState {
    return value as ToolInvocationState;
}

