// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreated
 */
export interface UserCreated {
    /**
     * 
     * @type {number}
     * @memberof UserCreated
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserCreated
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreated
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreated
     */
    avatarUrl?: string | null;
}

/**
 * Check if a given object implements the UserCreated interface.
 */
export function instanceOfUserCreated(value: object): value is UserCreated {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('login' in value) || value['login'] === undefined) return false;
    return true;
}

export function UserCreatedFromJSON(json: any): UserCreated {
    return UserCreatedFromJSONTyped(json, false);
}

export function UserCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreated {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'login': json['login'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
    };
}

export function UserCreatedToJSON(json: any): UserCreated {
    return UserCreatedToJSONTyped(json, false);
}

export function UserCreatedToJSONTyped(value?: UserCreated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'login': value['login'],
        'name': value['name'],
        'avatar_url': value['avatarUrl'],
    };
}

